---
output: html_document
---

<link rel="stylesheet" href="style.css">
<script src="https://kit.fontawesome.com/6e8b08f469.js" crossorigin="anonymous"></script>

<h2><b>Projects</b></h2>

<table>
<col width="20%">
<col width="30%">
<col width="50%">
<tr style="border-top:1pt solid black;">
  <th rowspan="2">Mar 2019 - Apr 2019</th>
  <td rowspan="2"; style="vertical-align: middle"><h4>Columbia University</h4></td>
  <td><h4><a href="https://github.com/valuntiny/p8160_group_project_2">Statistical Computing Group Project </a></h4></td>
</tr>
<tr>
  <td>Built a predictive model based on logistic regression to facilicate down syndrome diagnosis, and compared methods including and Pathwise Coordinate Descent with regularized logistic regression and smoothed bootstrap estimation. Found out that Smoothed Bootstrap Estimation provides a more accurate classification result, identified a subset of proteins that are significantly associated with the Down syndrome</td>
</tr>
<tr style="border-top:1pt solid black;">
  <th rowspan="2">Dec 2018 - Dec 2018</th>
  <td rowspan="2"; style="vertical-align: middle"><h4>Columbia University</h4></td>
  <td><h4><a href="https://github.com/Raarbiarsan1899/p8130_bm_group4">Biostatistical Methods Final project </a></h4></td>
</tr>
<tr>
  <td>Used the cancer statistics dataset containing information from cancer.gov, census.gov and clinicaltrials.gov to select a set of predictors that ‘best’ predicts cancer mortality. </td>
</tr>
<tr style="border-top:1pt solid black;">
  <th rowspan="2">Nov 2018 - Dec 2018</th>
  <td rowspan="2"; style="vertical-align: middle"><h4>Columbia University</h4></td>
  <td><h4><a href="http://shanj.tk/P8105_final_website.io/index.html">Data Science Final Project </a></h4></td>
</tr>
<tr>
  <td>Launched exploration from a general trend finding through data from National Occupational Employment Status and Wage Estimates from the US Bureau of Labour Statistics. Found out most required skills and majors for data-related jobs, and the difference in qualification between Fortune 500 and non-Fortune 500 companies. Finally used Dashboard and multiple visualization tools to represent the findings. </td>
</tr>
<tr style="border-top:1pt solid black;">
  <th rowspan="2">Oct 2018 - Oct 2018</th>
  <td rowspan="2"; style="vertical-align: middle"><h4>Columbia University</h4></td>
  <td><h4><a href="https://github.com/valuntiny/p8105_mtp_gw2383">Data Science Midterm Project </a></h4></td>
</tr>
<tr>
  <td>Used pipeline to study the patients' profile, applied statistical methods like linear regression and ANOVA on the activity data. Found out the patterns of physical activity over long periods of time. Helped to improve dynamic update of patient status.</td>
</tr>
<tr style="border-top:1pt solid black;">
  <th rowspan="2">Dec 2015 - May 2017</th>
  <td rowspan="2"; style="vertical-align: middle"><h4>Shanghai Jiao Tong University</h4></td>
  <td><h4><a href="http://cbb.sjtu.edu.cn/~jingli/webpages/guojing.html">Undergraduate Thesis </a></h4></td>
</tr>
<tr>
  <td>Proposed a biological network module-based zero-augmented generalized linear model, for differential expression analysis of count data. Conducted two simulation studies to compare the efficacy between zero-inflated model, hurdle model and negative binomial model. Then applied these to CPTAC colorectal cancer data set, and found 'negative binomial hurdle model' possesses higher efficacy and could identify modules with lower proportion size and effect size</td>
</tr>
</table>

<hr />
<hr />
<hr />

<h2><b>Course Works</b></h2>

<table>
<col width="25%">
<col width="35%">
<col width="20%">
<col width="20%">

<tr style="border-top:1pt solid black;">
  <th rowspan="8"><h4>Algorithm</h4></th>
  <td rowspan="8"; style="vertical-align: middle"><h4>Leetcode</h4></td>
  <td><a href="https://github.com/valuntiny/leetcode_string">string [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_string_ii">string [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_linked_list">linked list [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_linked_list_ii">linked list [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_tree">tree [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_tree_map">tree [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_sort_search">sort and search [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_sort_search_ii">sort and search [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_dynamic_prog">dynamic programming [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_dynamic_prog_ii">dynamic programming [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_design">design [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_design_ii">design [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_math">math [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_math_ii">math [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_other">other [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_other_ii">other [medium]</a></td>
</tr>

<tr style="border-top:1pt solid black;">
  <th rowspan="8"><h4>Algorithm</h4></th>
  <td rowspan="8"; style="vertical-align: middle"><h4>Leetcode</h4></td>
  <td><a href="https://github.com/valuntiny/leetcode_string">string [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_string_ii">string [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_linked_list">linked list [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_linked_list_ii">linked list [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_tree">tree [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_tree_map">tree [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_sort_search">sort and search [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_sort_search_ii">sort and search [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_dynamic_prog">dynamic programming [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_dynamic_prog_ii">dynamic programming [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_design">design [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_design_ii">design [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_math">math [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_math_ii">math [medium]</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/leetcode_other">other [easy]</a></td>
  <td><a href="https://github.com/valuntiny/leetcode_other_ii">other [medium]</a></td>
</tr>

<tr style="border-top:1pt solid black;">
  <th rowspan="3"><h4>Machine Learning</h4></th>
  <td rowspan="3"; style="vertical-align: middle"><h4>Kaggle</h4></td>
  <td><a href="https://github.com/valuntiny/kaggle_decision_tree">decision tree</a></td>
  <td><a href="https://github.com/valuntiny/kaggle_random_forest">random forest</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/kaggle_pandas">Pandas</a></td>
  <td><a href="https://github.com/valuntiny/kaggle_XGBoost">XGBoost</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/kaggle_data_visualization">visualization</a></td>
  <td><a href="https://github.com/valuntiny/kaggle_intermediate_ML">machine learning</a></td>
</tr>

<tr style="border-top:1pt solid black;">
  <th rowspan="4"><h4>Data Science</h4></th>
  <td rowspan="4"; style="vertical-align: middle"><h4>P8105 Data Science I</h4></td>
  <td><a href="https://github.com/valuntiny/p8105_Data_wrangling_2">data wrangling</a></td>
  <td><a href="https://github.com/valuntiny/p8105_data_manipulaton">data manipulation</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/p8105_tidy_data">tidying data</a></td>
  <td><a href="https://github.com/valuntiny/p8105_Visualization">visualization</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/p8105_group_by">group by</a></td>
  <td><a href="https://github.com/valuntiny/p8105_iteration">iteration</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/p8105_linear_models">linear model</a></td>
  <td><a href="https://github.com/valuntiny/p8105_shiny">shiny</a></td>
</tr>

<tr style="border-top:1pt solid black;">
  <th rowspan="5"><h4>Biostatistics</h4></th>
  <td rowspan="5"; style="vertical-align: middle"><h4>P8131 Biostatistical Methods II</h4></td>
  <td><a href="https://github.com/valuntiny/p8131_HW1">HW1</a></td>
  <td><a href="https://github.com/valuntiny/p8131_HW2">HW2</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/p8131_HW3">HW3</a></td>
  <td><a href="https://github.com/valuntiny/p8131_HW4">HW4</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/p8131_HW5">HW5</a></td>
  <td><a href="https://github.com/valuntiny/p8131_HW6">HW6</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/p8131_HW7">HW7</a></td>
  <td><a href="https://github.com/valuntiny/p8131_HW8">HW8</a></td>
</tr>
<tr>
  <td><a href="https://github.com/valuntiny/p8131_HW9">HW9</a></td>
  <td><a href="https://github.com/valuntiny/p8131_HW10">HW10</a></td>
</tr>
</table>