---
title: "Welcome to Georgen's personal website"
---

```{r setup, include = FALSE}

```

<style>
th {
  text-align: left;
}

th, td {
  padding: 10px;
  font-size: 15px;
}

td {
  vertical-align: top;
  height: 30px;
}

tr:hover {background-color: #f5f5f5;}
</style>

<h5>Click on any link for more information.</h5>

<hr />

<h2><b>Projects</b></h2>

<table>
<col width="20%">
<col width="30%">
<col width="50%">
<tr>
  <th>Mar 2019 - Apr 2019</th>
  <td><h4>Columbia University</h4></td>
  <td><h4><a href="https://github.com/valuntiny/p8160_group_project_2">Statistical Computing Group Project </a></h4></td>
</tr>
<tr>
  <th></th>
  <td></td>
  <td>asdasds</td>
</tr>
<tr>
  <th>Dec 2018 - Dec 2018</th>
  <td><h4>Columbia University</h4></td>
  <td><h4><a href="https://github.com/Raarbiarsan1899/p8130_bm_group4">Biostatistical Methods Final project </a></h4></td>
</tr>
<tr>
  <th></th>
  <td></td>
  <td>asdasds</td>
</tr>
<tr>
  <th>Nov 2018 - Dec 2018</th>
  <td><h4>Columbia University</h4></td>
  <td><h4><a href="http://shanj.tk/P8105_final_website.io/index.html">Data Science Final Project </a></h4></td>
</tr>
<tr>
  <th></th>
  <td></td>
  <td>asdasds</td>
</tr>
<tr>
  <th>Oct 2018 - Oct 2018</th>
  <td><h4>Columbia University</h4></td>
  <td><h4><a href="https://github.com/valuntiny/p8105_mtp_gw2383">Data Science Midterm Project </a></h4></td>
</tr>
<tr>
  <th></th>
  <td></td>
  <td>Used pipeline to study the patients' profile, applied statistical methods like linear regression and ANOVA on the activity data. Found out the patterns of physical activity over long periods of time. Helped to improve dynamic update of patient status.</td>
</tr>
<tr>
  <th>Dec 2015 - May 2017</th>
  <td><h4>Shanghai Jiao Tong University</h4></td>
  <td><h4><a href="http://cbb.sjtu.edu.cn/~jingli/webpages/guojing.html">Undergraduate Thesis </a></h4></td>
</tr>
<tr>
  <th></th>
  <td></td>
  <td>Proposed a biological network module-based zero-augmented generalized linear model, for differential expression analysis of count data. Conducted two simulation studies to compare the efficacy between zero-inflated model, hurdle model and negative binomial model. Then applied these to CPTAC colorectal cancer data set, and found 'negative binomial hurdle model' possesses higher efficacy and could identify modules with lower proportion size and effect size</td>
</tr>
</table>
<hr />

<h2><b>Experiences</b></h2>

<table>
<tr>
  <th><h4>Algorithm</h4></th>
  <td>
    
  </td>
  <td></td>
</tr>

<tr>
  <th><h4>Machine Learning</h4></th>
  <td>Source: E4540 Data Mining</td>
  <td><h4></h4></td>
</tr>

<tr>
  <th><h4>Statistical Computing</h4></th>
  <td>Source: P8160 Topics in Advanced Statistical Computing</td>
  <td><h4></h4></td>
</tr>

<tr>
  <th><h4>statistical modeling</h4></th>
  <td>Source: P8130 P8131 Biostatistical Methods</td>
  <td><h4></h4></td>
</tr>
</table>